# -*- coding: utf-8 -*-
"""AI_Lab6_tasks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bk6_B2WTY7qnZ9jOxa1ucMzxIFWxrPGW
"""

# task1

import random

def f(x):
    return -x**2 + 6*x

min_x = 0
max_x = 6

x = random.randint(min_x, max_x)

print("Initial x:", x)
print("f(x):", f(x))

while True:
    neighbors = []

    if x - 1 >= min_x:
        neighbors.append(x - 1)
    if x + 1 <= max_x:
        neighbors.append(x + 1)

    best_neighbor = x
    best_value = f(x)

    for n in neighbors:
        value = f(n)
        print("Checking neighbor:", n, "f(x) =", value)

        if value > best_value:
            best_neighbor = n
            best_value = value

    if best_neighbor == x:
        break

    x = best_neighbor
    print("Move to:", x, "f(x) =", f(x))
    print()

print("\nFinal Optimal x:", x)
print("Maximum value:", f(x))

goal = 20
beam_width = 2

def heuristic(n):
    return abs(goal - n)

beam = [(1, [1])]
visited = set([1])

level = 0
found = False

while beam and not found:
    print("\nLevel", level)
    new_states = []

    for state, path in beam:
        print("Exploring:", state)

        children = [state + 2, state + 3, state * 2]

        for child in children:

            if child > goal or child in visited:
                continue

            visited.add(child)
            new_path = path + [child]

            if child == goal:
                print("\nGoal Reached!")
                print("Path:", new_path)
                found = True
                break

            new_states.append((child, new_path))

        if found:
            break

    if found:
        break

    new_states.sort(key=lambda x: heuristic(x[0]))
    beam = new_states[:beam_width]

    print("Selected states:")
    for state, _ in beam:
        print(state, "h =", heuristic(state))

    level += 1

# task 3

import random

POP_SIZE = 6
GENS = 15
MUT_RATE = 0.1

def fitness(x):
    return x**2 + 2*x

def random_chromosome():
    return format(random.randint(0,31), '05b')

def decode(ch):
    return int(ch,2)

def selection(pop):
    pop.sort(key=lambda x: fitness(decode(x)), reverse=True)
    return pop[:2]

def crossover(p1,p2):
    point = random.randint(1,4)
    c1 = p1[:point] + p2[point:]
    c2 = p2[:point] + p1[point:]
    return c1,c2

def mutation(ch):
    ch = list(ch)
    for i in range(len(ch)):
        if random.random() < MUT_RATE:
            ch[i] = '1' if ch[i]=='0' else '0'
    return "".join(ch)

population = [random_chromosome() for _ in range(POP_SIZE)]

for gen in range(GENS):

    print("\nGeneration", gen)

    for ch in population:
        x = decode(ch)
        print(ch, "x =", x, "fitness =", fitness(x))

    parents = selection(population)

    new_pop = parents.copy()

    while len(new_pop) < POP_SIZE:
        c1,c2 = crossover(parents[0],parents[1])
        c1 = mutation(c1)
        c2 = mutation(c2)
        new_pop.extend([c1,c2])

    population = new_pop[:POP_SIZE]

best = max(population, key=lambda x: fitness(decode(x)))

print("\nBest Chromosome:", best)
print("Best x:", decode(best))
print("Best Fitness:", fitness(decode(best)))